### ISSUE TITLE
formatting with alignment fails

### ISSUE THREAD

**Issue by parkr** [rust-lang/time#98]
hey, I'm learning rust and re-writing a very basic `cal` in order to learn. ran into a strange formatting bug:

```rust
extern crate time;

fn main() {
    // not aligned (bug in TmFmt Display impl?)
    println!("{:>11}", time::now_utc().strftime("%B").ok().unwrap());
    // aligned properly when forced into a string
    println!("{:>11}", time::now_utc().strftime("%B").ok().unwrap().to_string());
}
```

know what's going on here? i don't think i should have to call `.to_string()` in order to get the alignment...?

**Comment by lifthrasiir** [comment]
To be exact, it is a common behavior that formatting implementations discard the width and alignment information:

```rust
fn main() {
    println!("{:>11?}", "a\nb\nc"); // not aligned
    println!("{:>11}", format!("{:?}", "a\nb\nc")); // aligned
}
```

I would argue that this behavior is, while frustrating, justifiable because alignment requires the length of printed string beforehand and this might not be acceptable for many types. But it *is* frustrating, and I agree that this has to be discussed and at least documented.

**Comment by vks** [comment]
If a type does not support alignment, then `println!` should fail at compile time IMHO.
Alas, this would not be backwards compatible. So we can only make it give a warning.

**Comment by alexcrichton** [comment]
Yes @lifthrasiir is right in that most types do not support the width/alignment of the underlying formatting system, and the best solution to this (as you've found) is to call `.to_string()` and then pad that accordingly. This is currently as-intended, however, and the documentation should probably happen in `std::fmt` instead of just in this library, so I'm going to close this issue.

**Comment by parkr** [comment]
> This is currently as-intended, however

Poop. Ok, that was really frustrating. Maybe a warning? A warning would have saved a lot of angst.

> the documentation should probably happen in std::fmt instead of just in this library, so I'm going to close this issue.

Where can I submit a PR for that?

**Comment by alexcrichton** [comment]
> Maybe a warning? A warning would have saved a lot of angst

Unfortunately there's no way for the formatting infrastructure to know whether a type actually looks at the formatting flags or not (as it's all trait-based).

> Where can I submit a PR for that?

A PR editing [this file](https://github.com/rust-lang/rust/blob/master/src/libcollections/fmt.rs) should do the trick!
